### ISSUE TITLE
how to microarray data classification based on association rule mining ?

### ISSUE THREAD

**Issue by alagukumarsanmugavel** [b3aver/uarray#3]

**Comment by b3aver** [comment]
This library is based on the project [MIDClass](http://ferrolab.dmi.unict.it/MIDClass.html).
You can find more details in this [article](http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0069873).

Hope it helps.

**Comment by alagukumarsanmugavel** [comment]
Could you please, How is working Associative Classification in data mining ? Can you give one example for that .. thanks in advance.

**Comment by alagukumarsanmugavel** [comment]
![limma](https://cloud.githubusercontent.com/assets/4829634/5161288/fe3351e4-73ca-11e4-90c4-b0681af2cf40.png)
When installing devtools, its showing error like this.
